#!/usr/bin/env python3
"""
set_key.py — safely add or update API keys in user_data/.env.

Used by:
  - Claude in chat, when the user pastes a key during onboarding
  - Manual invocation, if the user prefers a CLI to editing .env

Preserves any other variables already in .env. Validates that Anthropic
keys start with 'sk-ant-'. Keeps .env at chmod 600.

Usage:
    ./venv/bin/python scripts/set_key.py --exa <key>
    ./venv/bin/python scripts/set_key.py --anthropic <key>
    ./venv/bin/python scripts/set_key.py --exa <ek> --anthropic <ak>
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
USER_DATA = SKILL_ROOT / "user_data"
ENV_PATH = USER_DATA / ".env"


def _parse_env(text: str) -> dict[str, str]:
    """Parse a .env file into a dict. Preserves comments by returning them
    on synthetic keys so we can re-emit them. For this script we only care
    about KEY=VALUE lines."""
    result: dict[str, str] = {}
    for line in text.splitlines():
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        result[k.strip()] = v.strip()
    return result


def _write_env(values: dict[str, str]) -> None:
    """Write .env preserving the header comments and chmod 600."""
    header = (
        "# Auto-generated by setup.py — do not commit.\n"
        "# Fill in the values below if they are empty.\n"
        "# Either edit this file directly, or run:\n"
        "#   ./venv/bin/python scripts/set_key.py --exa <key> --anthropic <key>\n"
    )
    body_lines = [f"{k}={v}" for k, v in values.items()]
    ENV_PATH.write_text(header + "\n".join(body_lines) + "\n")
    os.chmod(ENV_PATH, 0o600)


def main() -> int:
    parser = argparse.ArgumentParser(description="Set API keys in user_data/.env")
    parser.add_argument("--exa", help="Exa API key")
    parser.add_argument("--anthropic", help="Anthropic API key (starts with sk-ant-)")
    args = parser.parse_args()

    if not args.exa and not args.anthropic:
        print("ERROR: pass at least one of --exa or --anthropic.", file=sys.stderr)
        return 1

    # Validate Anthropic format
    if args.anthropic and not args.anthropic.startswith("sk-ant-"):
        print(
            "ERROR: --anthropic looks malformed — Anthropic keys start with 'sk-ant-'.\n"
            "Get a key at https://console.anthropic.com.",
            file=sys.stderr,
        )
        return 1

    # Ensure user_data exists (defensive — setup.py should have created it)
    USER_DATA.mkdir(exist_ok=True)

    # Load existing .env, or start fresh with both keys empty
    if ENV_PATH.exists():
        values = _parse_env(ENV_PATH.read_text())
    else:
        values = {}

    # Ensure both keys are present (use existing value if not overriding)
    values.setdefault("EXA_API_KEY", "")
    values.setdefault("ANTHROPIC_API_KEY", "")

    # Apply updates
    updates = []
    if args.exa:
        values["EXA_API_KEY"] = args.exa
        updates.append("EXA_API_KEY")
    if args.anthropic:
        values["ANTHROPIC_API_KEY"] = args.anthropic
        updates.append("ANTHROPIC_API_KEY")

    _write_env(values)

    print(f"Updated {', '.join(updates)} in {ENV_PATH.relative_to(SKILL_ROOT)} (chmod 600).")

    # Report status of both keys
    exa_status = "filled" if values.get("EXA_API_KEY") else "still empty"
    ant_status = "filled" if values.get("ANTHROPIC_API_KEY") else "still empty"
    print(f"  EXA_API_KEY:       {exa_status}")
    print(f"  ANTHROPIC_API_KEY: {ant_status}")

    if values.get("EXA_API_KEY") and values.get("ANTHROPIC_API_KEY"):
        print("\nBoth keys present. Ready to run: ./venv/bin/python scripts/find_ideas.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
